### ISSUE TITLE
example of how to retrieve data based on a filter

### ISSUE THREAD

**Issue by mattgi** [xdissent/spinnaker#1]
Hi,

Can you please provide an example of how to retrieve data based on a filter/query?

```
  GameDetails.get({gameId: $scope.game.id}, function(gameDetails) {
    $scope.gameDetails = gameDetails;
```

fails.

```
  GameDetails.query({gameId: $scope.game.id}, function(gameDetails) {
    $scope.gameDetails = gameDetails;
```

returns all data (i.e. does not apply the filter).

Bit lost on how to get this to work.

**Comment by adampilks** [comment]
:+1:  Would also be interested in this

**Comment by jonlong** [comment]
Yup, running into this myself.

**Comment by jonlong** [comment]
Just submitted a pull request that addresses this.  @mattgi @adampilks It should work as expected (pass an object with a filter config). I think the issue was just that the code wasn't expecting filters for GET reqs.

**Comment by joshua1** [comment]
Hi jonlong,
has this been pulled into spinnaker. i cant seem to find any other library that does what this does the way it does and it seems Greg the creator no longer supports it

**Comment by jonlong** [comment]
@joshua1 No, not yet—if it's something you need, you can pull my fork or take a look at this lib, which seems to have added it with the last commit: https://github.com/kyjan/angular-sails

**Comment by joshua1** [comment]
@jonlong thanks for the response. i have looked at that but had some challenges with require. I am using the ngStart skeleton which uses requirejs

**Comment by joshua1** [comment]
@jonlong Do you have a build of your own fork of spinnaker?

**Comment by jonlong** [comment]
@joshua1 If by build, you mean minified/uglified, then no—that still breaks it. #3 is open to address that, but I never ended up pursuing a fix because I went with angular-sails instead.  My fork that adds get as a queryable method is here:

https://github.com/jonlong/spinnaker/tree/get-query

**Comment by joshua1** [comment]
@jonlong  i have used your fork of spinnaker and am good with it. Thanks
